import type { SnippetLanguage } from "./snippets";

/**
 * A small syntax highlighter for the snippet languages.
 *
 * Deliberately not Prism or Shiki. Both are far heavier than this needs to be,
 * and the input here is not arbitrary user code — it is generated by
 * lib/tools/snippets.ts, so the grammar it has to cope with is known and
 * small. Worst case a token is mis-coloured; nothing can break.
 */

export type TokenType =
  | "comment"
  | "string"
  | "number"
  | "keyword"
  | "variable"
  | "flag"
  | "punctuation"
  | "plain";

export type Token = { type: TokenType; value: string };

type Rule = { type: TokenType; pattern: RegExp };

const KEYWORDS: Record<SnippetLanguage, string[]> = {
  curl: ["curl"],
  powershell: [
    "Invoke-RestMethod",
    "Invoke-WebRequest",
    "ConvertFrom-Json",
    "Get-Content",
    "Sort-Object",
  ],
  python: ["import", "with", "open", "as", "requests", "tuple", "set", "list", "for", "in", "print"],
  javascript: [
    "const",
    "await",
    "new",
    "fetch",
    "method",
    "headers",
    "body",
    "for",
    "of",
    "Object",
    "Map",
    "Set",
    "console",
  ],
  go: [
    "import",
    "var",
    "struct",
    "if",
    "err",
    "nil",
    "defer",
    "func",
    "string",
    "map",
    "log",
    "json",
    "http",
    "os",
    "bytes",
    "io",
    "fmt",
  ],
  ruby: [
    "require",
    "raise",
    "unless",
    "do",
    "end",
    "puts",
    "URI",
    "Net",
    "HTTP",
    "JSON",
    "File",
    "each",
    "first",
  ],
  rust: [
    "use",
    "let",
    "struct",
    "fn",
    "pub",
    "mut",
    "String",
    "Vec",
    "HashMap",
    "Deserialize",
    "serde",
    "std",
    "reqwest",
    "blocking",
  ],
};

function keywordPattern(language: SnippetLanguage): RegExp {
  // Longest first, so "Invoke-RestMethod" is not partly matched by "Invoke".
  const words = [...KEYWORDS[language]].sort((a, b) => b.length - a.length);
  const escaped = words.map((word) => word.replace(/[.*+?^${}()|[\]\\-]/g, "\\$&"));
  return new RegExp(`^(?:${escaped.join("|")})\\b`);
}

function rulesFor(language: SnippetLanguage): Rule[] {
  // Order matters: comments and strings must be consumed before anything else
  // gets a chance to match inside them.
  const common: Rule[] = [
    { type: "string", pattern: /^"(?:[^"\\]|\\.)*"/ },
    { type: "string", pattern: /^'(?:[^'\\]|\\.)*'/ },
    { type: "number", pattern: /^\b\d+(?:\.\d+)?\b/ },
  ];

  switch (language) {
    case "curl":
      return [
        { type: "comment", pattern: /^#[^\n]*/ },
        ...common,
        // -s, --data-binary, and the trailing line-continuation backslash.
        { type: "flag", pattern: /^--?[a-zA-Z][\w-]*/ },
        { type: "keyword", pattern: keywordPattern("curl") },
        { type: "punctuation", pattern: /^[\\|]/ },
      ];

    case "powershell":
      return [
        { type: "comment", pattern: /^#[^\n]*/ },
        ...common,
        { type: "variable", pattern: /^\$[A-Za-z_][\w]*/ },
        { type: "flag", pattern: /^-[A-Za-z][\w-]*/ },
        { type: "keyword", pattern: keywordPattern("powershell") },
        { type: "punctuation", pattern: /^[|`{}[\]().,]/ },
      ];

    case "python":
      return [
        { type: "comment", pattern: /^#[^\n]*/ },
        ...common,
        { type: "keyword", pattern: keywordPattern("python") },
        { type: "punctuation", pattern: /^[{}[\]().,:=]/ },
      ];

    case "javascript":
      return [
        { type: "comment", pattern: /^\/\/[^\n]*/ },
        ...common,
        { type: "string", pattern: /^`(?:[^`\\]|\\.)*`/ },
        { type: "keyword", pattern: keywordPattern("javascript") },
        { type: "punctuation", pattern: /^[{}[\]().,;:=]/ },
      ];

    case "go":
      return [
        { type: "comment", pattern: /^\/\/[^\n]*/ },
        // Go struct tags are backticked and must beat the generic string rules.
        { type: "string", pattern: /^`[^`]*`/ },
        ...common,
        { type: "keyword", pattern: keywordPattern("go") },
        { type: "punctuation", pattern: /^[{}[\]().,;:=&*]/ },
      ];

    case "ruby":
      return [
        { type: "comment", pattern: /^#(?!\{)[^\n]*/ },
        ...common,
        // |key, value| block parameters, which read as variables.
        { type: "variable", pattern: /^\|[^|\n]*\|/ },
        { type: "keyword", pattern: keywordPattern("ruby") },
        { type: "punctuation", pattern: /^[{}[\]().,;:=>]/ },
      ];

    case "rust":
      return [
        { type: "comment", pattern: /^\/\/[^\n]*/ },
        ...common,
        // #[derive(...)] is an attribute; keep it one token rather than
        // letting the punctuation rule shred it.
        { type: "flag", pattern: /^#\[[^\]\n]*\]/ },
        { type: "keyword", pattern: keywordPattern("rust") },
        { type: "punctuation", pattern: /^[{}[\]().,;:=&<>?]/ },
      ];
  }
}

/**
 * Tokenises a snippet. Anything no rule matches is emitted as "plain", one
 * character at a time, then merged — so every character of the input always
 * survives to the output.
 */
export function tokenize(code: string, language: SnippetLanguage): Token[] {
  const rules = rulesFor(language);
  const tokens: Token[] = [];
  let rest = code;

  while (rest.length > 0) {
    let matched = false;

    for (const rule of rules) {
      const match = rule.pattern.exec(rest);
      if (match && match[0].length > 0) {
        tokens.push({ type: rule.type, value: match[0] });
        rest = rest.slice(match[0].length);
        matched = true;
        break;
      }
    }

    if (!matched) {
      const previous = tokens[tokens.length - 1];
      if (previous && previous.type === "plain") {
        previous.value += rest[0];
      } else {
        tokens.push({ type: "plain", value: rest[0] });
      }
      rest = rest.slice(1);
    }
  }

  return tokens;
}
